### ISSUE TITLE
No retrurn button

### ISSUE THREAD

**Issue by ericfaure** [wpeasysoft/woocommerce-return-warranty-management#1]
Hi,
Your plugin seems very good, but I have problems to make it work. I made some tested orders on my shop under construction. I do not see buttons "return" on the page "my account" -> "orders". I am under wordpress 5.2.2 with PHP 7.3. Woocommerce updated and activated. Theme twenty seventeen. I have configured the plugin (status, warranty period ...). Aside from displaying the warranty period on the product page, your plugin does not seem to work well.
thank you for your reply

**Comment by wpeasysoft** [comment]
Hi @ericfaure 
I think you need to set order status from `Return & Warranty -> Settings` for which statuses you want to show Return button in my account order page. If you set only for `Completed` and `Processing` status than for only `Completed` and `Processing` orders you will show Request a Warranty button. 

If you face any problem then, please let me know.

**Comment by ashutosh2307** [comment]
Facing the same. I selected completed orders but no return button showing there.

**Comment by wpeasysoft** [comment]
Variable product feature is not in free version. Its comes with pro version. You can check this link 
https://wpeasysoft.com/downloads/woocommerce-return-warranty-management/ 

Thanks
